/**
 * generated by Xtext 2.14.0
 */
package mindMap_CarteMentale.ide;

import mindMap_CarteMentale.ide.AbstractMyDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyDslIdeModule extends AbstractMyDslIdeModule {
}
