/*
 * generated by Xtext 2.14.0
 */
package mindMap_CarteMentale.ui;

import com.google.inject.Injector;
import mindMap_CarteMentale.ui.internal.MindMap_CarteMentaleActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(MindMap_CarteMentaleActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		MindMap_CarteMentaleActivator activator = MindMap_CarteMentaleActivator.getInstance();
		return activator != null ? activator.getInjector(MindMap_CarteMentaleActivator.MINDMAP_CARTEMENTALE_MYDSL) : null;
	}

}
