/**
 * generated by Xtext 2.14.0
 */
package mindMap_CarteMentale.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Marker</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mindMap_CarteMentale.myDsl.Marker#getSymbol <em>Symbol</em>}</li>
 * </ul>
 *
 * @see mindMap_CarteMentale.myDsl.MyDslPackage#getMarker()
 * @model
 * @generated
 */
public interface Marker extends EObject
{
  /**
   * Returns the value of the '<em><b>Symbol</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Symbol</em>' attribute.
   * @see #setSymbol(int)
   * @see mindMap_CarteMentale.myDsl.MyDslPackage#getMarker_Symbol()
   * @model
   * @generated
   */
  int getSymbol();

  /**
   * Sets the value of the '{@link mindMap_CarteMentale.myDsl.Marker#getSymbol <em>Symbol</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Symbol</em>' attribute.
   * @see #getSymbol()
   * @generated
   */
  void setSymbol(int value);

} // Marker
