/**
 * generated by Xtext 2.14.0
 */
package mindMap_CarteMentale.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see mindMap_CarteMentale.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.MyDsl.mindMap_CarteMentale";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = mindMap_CarteMentale.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link mindMap_CarteMentale.myDsl.impl.MindMapImpl <em>Mind Map</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mindMap_CarteMentale.myDsl.impl.MindMapImpl
   * @see mindMap_CarteMentale.myDsl.impl.MyDslPackageImpl#getMindMap()
   * @generated
   */
  int MIND_MAP = 0;

  /**
   * The feature id for the '<em><b>Markers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MIND_MAP__MARKERS = 0;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MIND_MAP__TITLE = 1;

  /**
   * The feature id for the '<em><b>Centraltopic</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MIND_MAP__CENTRALTOPIC = 2;

  /**
   * The number of structural features of the '<em>Mind Map</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MIND_MAP_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link mindMap_CarteMentale.myDsl.impl.CentralTopicImpl <em>Central Topic</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mindMap_CarteMentale.myDsl.impl.CentralTopicImpl
   * @see mindMap_CarteMentale.myDsl.impl.MyDslPackageImpl#getCentralTopic()
   * @generated
   */
  int CENTRAL_TOPIC = 1;

  /**
   * The feature id for the '<em><b>Markers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CENTRAL_TOPIC__MARKERS = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CENTRAL_TOPIC__NAME = 1;

  /**
   * The feature id for the '<em><b>Maintopic</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CENTRAL_TOPIC__MAINTOPIC = 2;

  /**
   * The number of structural features of the '<em>Central Topic</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CENTRAL_TOPIC_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link mindMap_CarteMentale.myDsl.impl.MainTopicImpl <em>Main Topic</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mindMap_CarteMentale.myDsl.impl.MainTopicImpl
   * @see mindMap_CarteMentale.myDsl.impl.MyDslPackageImpl#getMainTopic()
   * @generated
   */
  int MAIN_TOPIC = 2;

  /**
   * The feature id for the '<em><b>Markers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_TOPIC__MARKERS = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_TOPIC__NAME = 1;

  /**
   * The feature id for the '<em><b>Subtopic</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_TOPIC__SUBTOPIC = 2;

  /**
   * The number of structural features of the '<em>Main Topic</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_TOPIC_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link mindMap_CarteMentale.myDsl.impl.SubTopicImpl <em>Sub Topic</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mindMap_CarteMentale.myDsl.impl.SubTopicImpl
   * @see mindMap_CarteMentale.myDsl.impl.MyDslPackageImpl#getSubTopic()
   * @generated
   */
  int SUB_TOPIC = 3;

  /**
   * The feature id for the '<em><b>Markers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_TOPIC__MARKERS = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_TOPIC__NAME = 1;

  /**
   * The feature id for the '<em><b>Subtopic</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_TOPIC__SUBTOPIC = 2;

  /**
   * The number of structural features of the '<em>Sub Topic</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_TOPIC_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link mindMap_CarteMentale.myDsl.impl.MarkerImpl <em>Marker</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mindMap_CarteMentale.myDsl.impl.MarkerImpl
   * @see mindMap_CarteMentale.myDsl.impl.MyDslPackageImpl#getMarker()
   * @generated
   */
  int MARKER = 4;

  /**
   * The feature id for the '<em><b>Symbol</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MARKER__SYMBOL = 0;

  /**
   * The number of structural features of the '<em>Marker</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MARKER_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link mindMap_CarteMentale.myDsl.MindMap <em>Mind Map</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mind Map</em>'.
   * @see mindMap_CarteMentale.myDsl.MindMap
   * @generated
   */
  EClass getMindMap();

  /**
   * Returns the meta object for the containment reference list '{@link mindMap_CarteMentale.myDsl.MindMap#getMarkers <em>Markers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Markers</em>'.
   * @see mindMap_CarteMentale.myDsl.MindMap#getMarkers()
   * @see #getMindMap()
   * @generated
   */
  EReference getMindMap_Markers();

  /**
   * Returns the meta object for the attribute '{@link mindMap_CarteMentale.myDsl.MindMap#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see mindMap_CarteMentale.myDsl.MindMap#getTitle()
   * @see #getMindMap()
   * @generated
   */
  EAttribute getMindMap_Title();

  /**
   * Returns the meta object for the containment reference '{@link mindMap_CarteMentale.myDsl.MindMap#getCentraltopic <em>Centraltopic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Centraltopic</em>'.
   * @see mindMap_CarteMentale.myDsl.MindMap#getCentraltopic()
   * @see #getMindMap()
   * @generated
   */
  EReference getMindMap_Centraltopic();

  /**
   * Returns the meta object for class '{@link mindMap_CarteMentale.myDsl.CentralTopic <em>Central Topic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Central Topic</em>'.
   * @see mindMap_CarteMentale.myDsl.CentralTopic
   * @generated
   */
  EClass getCentralTopic();

  /**
   * Returns the meta object for the containment reference list '{@link mindMap_CarteMentale.myDsl.CentralTopic#getMarkers <em>Markers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Markers</em>'.
   * @see mindMap_CarteMentale.myDsl.CentralTopic#getMarkers()
   * @see #getCentralTopic()
   * @generated
   */
  EReference getCentralTopic_Markers();

  /**
   * Returns the meta object for the attribute '{@link mindMap_CarteMentale.myDsl.CentralTopic#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see mindMap_CarteMentale.myDsl.CentralTopic#getName()
   * @see #getCentralTopic()
   * @generated
   */
  EAttribute getCentralTopic_Name();

  /**
   * Returns the meta object for the containment reference list '{@link mindMap_CarteMentale.myDsl.CentralTopic#getMaintopic <em>Maintopic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Maintopic</em>'.
   * @see mindMap_CarteMentale.myDsl.CentralTopic#getMaintopic()
   * @see #getCentralTopic()
   * @generated
   */
  EReference getCentralTopic_Maintopic();

  /**
   * Returns the meta object for class '{@link mindMap_CarteMentale.myDsl.MainTopic <em>Main Topic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Main Topic</em>'.
   * @see mindMap_CarteMentale.myDsl.MainTopic
   * @generated
   */
  EClass getMainTopic();

  /**
   * Returns the meta object for the containment reference list '{@link mindMap_CarteMentale.myDsl.MainTopic#getMarkers <em>Markers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Markers</em>'.
   * @see mindMap_CarteMentale.myDsl.MainTopic#getMarkers()
   * @see #getMainTopic()
   * @generated
   */
  EReference getMainTopic_Markers();

  /**
   * Returns the meta object for the attribute '{@link mindMap_CarteMentale.myDsl.MainTopic#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see mindMap_CarteMentale.myDsl.MainTopic#getName()
   * @see #getMainTopic()
   * @generated
   */
  EAttribute getMainTopic_Name();

  /**
   * Returns the meta object for the containment reference list '{@link mindMap_CarteMentale.myDsl.MainTopic#getSubtopic <em>Subtopic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Subtopic</em>'.
   * @see mindMap_CarteMentale.myDsl.MainTopic#getSubtopic()
   * @see #getMainTopic()
   * @generated
   */
  EReference getMainTopic_Subtopic();

  /**
   * Returns the meta object for class '{@link mindMap_CarteMentale.myDsl.SubTopic <em>Sub Topic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sub Topic</em>'.
   * @see mindMap_CarteMentale.myDsl.SubTopic
   * @generated
   */
  EClass getSubTopic();

  /**
   * Returns the meta object for the containment reference list '{@link mindMap_CarteMentale.myDsl.SubTopic#getMarkers <em>Markers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Markers</em>'.
   * @see mindMap_CarteMentale.myDsl.SubTopic#getMarkers()
   * @see #getSubTopic()
   * @generated
   */
  EReference getSubTopic_Markers();

  /**
   * Returns the meta object for the attribute '{@link mindMap_CarteMentale.myDsl.SubTopic#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see mindMap_CarteMentale.myDsl.SubTopic#getName()
   * @see #getSubTopic()
   * @generated
   */
  EAttribute getSubTopic_Name();

  /**
   * Returns the meta object for the containment reference list '{@link mindMap_CarteMentale.myDsl.SubTopic#getSubtopic <em>Subtopic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Subtopic</em>'.
   * @see mindMap_CarteMentale.myDsl.SubTopic#getSubtopic()
   * @see #getSubTopic()
   * @generated
   */
  EReference getSubTopic_Subtopic();

  /**
   * Returns the meta object for class '{@link mindMap_CarteMentale.myDsl.Marker <em>Marker</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Marker</em>'.
   * @see mindMap_CarteMentale.myDsl.Marker
   * @generated
   */
  EClass getMarker();

  /**
   * Returns the meta object for the attribute '{@link mindMap_CarteMentale.myDsl.Marker#getSymbol <em>Symbol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Symbol</em>'.
   * @see mindMap_CarteMentale.myDsl.Marker#getSymbol()
   * @see #getMarker()
   * @generated
   */
  EAttribute getMarker_Symbol();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link mindMap_CarteMentale.myDsl.impl.MindMapImpl <em>Mind Map</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mindMap_CarteMentale.myDsl.impl.MindMapImpl
     * @see mindMap_CarteMentale.myDsl.impl.MyDslPackageImpl#getMindMap()
     * @generated
     */
    EClass MIND_MAP = eINSTANCE.getMindMap();

    /**
     * The meta object literal for the '<em><b>Markers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MIND_MAP__MARKERS = eINSTANCE.getMindMap_Markers();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MIND_MAP__TITLE = eINSTANCE.getMindMap_Title();

    /**
     * The meta object literal for the '<em><b>Centraltopic</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MIND_MAP__CENTRALTOPIC = eINSTANCE.getMindMap_Centraltopic();

    /**
     * The meta object literal for the '{@link mindMap_CarteMentale.myDsl.impl.CentralTopicImpl <em>Central Topic</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mindMap_CarteMentale.myDsl.impl.CentralTopicImpl
     * @see mindMap_CarteMentale.myDsl.impl.MyDslPackageImpl#getCentralTopic()
     * @generated
     */
    EClass CENTRAL_TOPIC = eINSTANCE.getCentralTopic();

    /**
     * The meta object literal for the '<em><b>Markers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CENTRAL_TOPIC__MARKERS = eINSTANCE.getCentralTopic_Markers();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CENTRAL_TOPIC__NAME = eINSTANCE.getCentralTopic_Name();

    /**
     * The meta object literal for the '<em><b>Maintopic</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CENTRAL_TOPIC__MAINTOPIC = eINSTANCE.getCentralTopic_Maintopic();

    /**
     * The meta object literal for the '{@link mindMap_CarteMentale.myDsl.impl.MainTopicImpl <em>Main Topic</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mindMap_CarteMentale.myDsl.impl.MainTopicImpl
     * @see mindMap_CarteMentale.myDsl.impl.MyDslPackageImpl#getMainTopic()
     * @generated
     */
    EClass MAIN_TOPIC = eINSTANCE.getMainTopic();

    /**
     * The meta object literal for the '<em><b>Markers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIN_TOPIC__MARKERS = eINSTANCE.getMainTopic_Markers();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAIN_TOPIC__NAME = eINSTANCE.getMainTopic_Name();

    /**
     * The meta object literal for the '<em><b>Subtopic</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIN_TOPIC__SUBTOPIC = eINSTANCE.getMainTopic_Subtopic();

    /**
     * The meta object literal for the '{@link mindMap_CarteMentale.myDsl.impl.SubTopicImpl <em>Sub Topic</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mindMap_CarteMentale.myDsl.impl.SubTopicImpl
     * @see mindMap_CarteMentale.myDsl.impl.MyDslPackageImpl#getSubTopic()
     * @generated
     */
    EClass SUB_TOPIC = eINSTANCE.getSubTopic();

    /**
     * The meta object literal for the '<em><b>Markers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUB_TOPIC__MARKERS = eINSTANCE.getSubTopic_Markers();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUB_TOPIC__NAME = eINSTANCE.getSubTopic_Name();

    /**
     * The meta object literal for the '<em><b>Subtopic</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUB_TOPIC__SUBTOPIC = eINSTANCE.getSubTopic_Subtopic();

    /**
     * The meta object literal for the '{@link mindMap_CarteMentale.myDsl.impl.MarkerImpl <em>Marker</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mindMap_CarteMentale.myDsl.impl.MarkerImpl
     * @see mindMap_CarteMentale.myDsl.impl.MyDslPackageImpl#getMarker()
     * @generated
     */
    EClass MARKER = eINSTANCE.getMarker();

    /**
     * The meta object literal for the '<em><b>Symbol</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MARKER__SYMBOL = eINSTANCE.getMarker_Symbol();

  }

} //MyDslPackage
