/**
 * generated by Xtext 2.14.0
 */
package mindMap_CarteMentale.ui.contentassist;

import mindMap_CarteMentale.ui.contentassist.AbstractMyDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MyDslProposalProvider extends AbstractMyDslProposalProvider {
}
